In [75]:
# DEVOIR 2 - QUESTION 2
# PARTIE A: NETTOYAGE DES DONNÉES

import csv
import numpy as np
import pandas as pd

In [56]:
# Créer un tableau vide avec tous les pays/territoires
df_test = pd.read_csv('countries_test.csv')
df_test.head()
countries_matrix = df_test.values
countries_matrix

array([['Anguilla', ' Anguilla (UK)', nan, nan, nan],
       ['Aruba', ' Aruba (Netherlands)', nan, nan, nan],
       ['Channel Islands', ' Channel Islands (UK)',
        ' Channel Islands - (11) Guernsey (UK) and (12) Jersey (UK)',
        nan, nan],
       ['Bolivia', ' Plurinational State of Bolivia', nan, nan, nan],
       ['Congo', ' Congo-Kinshasa', ' Congo DR',
        ' Democratic Republic of Congo', ' DR Congo']], dtype=object)

In [54]:
countries = df_test.iloc[:,0].values
new_array = np.empty(countries.shape[0], dtype=float)
new_array[:] = np.NaN
new_array

array([nan, nan, nan, nan, nan])

In [67]:
df = pd.read_csv("test.csv")
df.head()
test_country = df.iloc[:,0].values
estimate = df.iloc[:,1].values

array([1., 2., 3., 4.])

In [79]:
print(test_country)
print(estimate)

['Anguilla (UK)' 'Channel Islands' 'DR Congo' 'World']
[1. 2. 3. 4.]


In [26]:
def clean_name(country_array, is_asterics):
    new_array = np.empty(country_array.shape[0], dtype=object)
    
    #1. Remove the asterics next to each name
    if is_asterics:
        for i in range(country_array.shape[0]):
            country = country_array[i]
            new_array[i] = country[:-2]
        
    return new_array

In [155]:
df_1 = pd.read_csv("CSV Brute Files/1.csv")
df_1.head()

Country/Territory         Subregion    Region    IMF[3] IMF[3].1  \
0  Country/Territory         Subregion    Region  Estimate     Year   
1           Monaco *    Western Europe    Europe       NaN      NaN   
2    Liechtenstein *    Western Europe    Europe       NaN      NaN   
3       Luxembourg *    Western Europe    Europe   131,782     2021   
4          Bermuda *  Northern America  Americas       NaN      NaN   

  United Nations[4] United Nations[4].1 World Bank[5] World Bank[5].1  
0          Estimate                Year      Estimate            Year  
1           190,532                2019       190,513            2019  
2           179,258                2019       180,367            2018  
3           115,481                2019       115,874            2020  
4           117,768                2019       117,098            2019

In [125]:
df_1 = pd.read_csv("CSV Brute Files/1.csv")
df_1.head()
df_1 = df_1.iloc[1:,[0,5]]
countries = df_1.iloc[:,0].values
test = countries[0]
print(type(test))
print(test)

<class 'str'>
Monaco *


In [126]:
new_countries = clean_name(countries, True)
new_countries.shape

(216,)

In [147]:
estimate = df_1.iloc[:,1].values
test2 = estimate[0]
print(test2)

190,532


In [150]:
test2 = float(str(test2).replace(',','.'))
print(test2)
print(type(test2))

190.532
<class 'float'>


In [171]:
new_estimate = np.zeros(estimate.shape[0], dtype=float)
for i in range(estimate.shape[0]):
    new_estimate[i] = float(str(estimate[i]).replace(',','.'))