In [75]:
# DEVOIR 2 - QUESTION 2
# PARTIE A: NETTOYAGE DES DONNÉES
import csv
import numpy as np
import pandas as pd

In [83]:
df = pd.read_csv("CSV Raw Data/1.csv")
df.head()
df = df.iloc[1:,[0,5]]
df

Country/Territory United Nations[4]
1            Monaco *           190,532
2     Liechtenstein *           179,258
3        Luxembourg *           115,481
4           Bermuda *           117,768
5       Switzerland *            85,135
..                ...               ...
212          Malawi *               435
213      Mozambique *               504
214         Somalia *               105
215     South Sudan *               448
216         Burundi *               260

[216 rows x 2 columns]

In [84]:
df = pd.read_csv("CSV Raw Data/2.csv")
df.head()
df = df.iloc[0:,[1,2]]
df

Country/Territory  Averagedownloadspeed(Mbit/s)(Ookla)[4]
0          Singapore                                  245.50
1        South Korea                                  241.58
2          Hong Kong                                  240.83
3             Monaco                                  220.35
4            Romania                                  214.33
..               ...                                     ...
95          Dominica                                   37.62
96   North Macedonia                                   37.20
97            Greece                                   36.73
98        Bangladesh                                   36.02
99           Senegal                                   35.32

[100 rows x 2 columns]

In [86]:
df = pd.read_csv("CSV Raw Data/3.csv")
df.head()
df = df.iloc[0:,[0,2]]
df

Country 2016[8]
0    Afghanistan     0.2
1        Albania     7.5
2        Algeria     0.9
3        Andorra    11.3
4         Angola     6.4
..           ...     ...
186    Venezuela     5.6
187      Vietnam     8.3
188        Yemen     0.1
189       Zambia     4.8
190     Zimbabwe     4.8

[191 rows x 2 columns]

In [89]:
df = pd.read_csv("CSV Raw Data/4.csv")
df.head()
df = df.iloc[1:,[0,3]]
df

Country or subnational area  Rate
1                 Afghanistan *   6.7
2                     Albania *   2.3
3                       Algeria   1.4
4                       Andorra   0.0
5                        Angola   4.8
..                          ...   ...
191                 Venezuela *  36.7
192                   Vietnam *   1.5
193                     Yemen *   6.8
194                      Zambia   5.4
195                  Zimbabwe *   7.5

[195 rows x 2 columns]

In [91]:
df = pd.read_csv("CSV Raw Data/5.csv")
df.head()
df = df.iloc[1:,[1,3]]
df

Country  % of GDP
1        United States       3.7
2                China       1.7
3                India       2.9
4   Russian Federation       4.3
5       United Kingdom       2.2
6         Saudi Arabia       8.4
7              Germany       1.4
8               France       2.1
9                Japan       1.0
10         South Korea       2.8
11               Italy       1.6
12           Australia       2.1
13              Canada       1.4
14              Israel       5.6
15              Brazil       1.4

In [56]:
# Créer un tableau vide avec tous les pays/territoires
df_test = pd.read_csv('countries_test.csv')
df_test.head()
countries_matrix = df_test.values
countries_matrix

array([['Anguilla', ' Anguilla (UK)', nan, nan, nan],
       ['Aruba', ' Aruba (Netherlands)', nan, nan, nan],
       ['Channel Islands', ' Channel Islands (UK)',
        ' Channel Islands - (11) Guernsey (UK) and (12) Jersey (UK)',
        nan, nan],
       ['Bolivia', ' Plurinational State of Bolivia', nan, nan, nan],
       ['Congo', ' Congo-Kinshasa', ' Congo DR',
        ' Democratic Republic of Congo', ' DR Congo']], dtype=object)

In [54]:
countries = df_test.iloc[:,0].values
new_array = np.empty(countries.shape[0], dtype=float)
new_array[:] = np.NaN
new_array

array([nan, nan, nan, nan, nan])

In [67]:
df = pd.read_csv("test.csv")
df.head()
test_country = df.iloc[:,0].values
estimate = df.iloc[:,1].values

array([1., 2., 3., 4.])

In [79]:
print(test_country)
print(estimate)

['Anguilla (UK)' 'Channel Islands' 'DR Congo' 'World']
[1. 2. 3. 4.]


In [26]:
def clean_name(country_array, is_asterics):
    new_array = np.empty(country_array.shape[0], dtype=object)
    
    #1. Remove the asterics next to each name
    if is_asterics:
        for i in range(country_array.shape[0]):
            country = country_array[i]
            new_array[i] = country[:-2]
        
    return new_array

In [155]:
df_1 = pd.read_csv("CSV Brute Files/1.csv")
df_1.head()

Country/Territory         Subregion    Region    IMF[3] IMF[3].1  \
0  Country/Territory         Subregion    Region  Estimate     Year   
1           Monaco *    Western Europe    Europe       NaN      NaN   
2    Liechtenstein *    Western Europe    Europe       NaN      NaN   
3       Luxembourg *    Western Europe    Europe   131,782     2021   
4          Bermuda *  Northern America  Americas       NaN      NaN   

  United Nations[4] United Nations[4].1 World Bank[5] World Bank[5].1  
0          Estimate                Year      Estimate            Year  
1           190,532                2019       190,513            2019  
2           179,258                2019       180,367            2018  
3           115,481                2019       115,874            2020  
4           117,768                2019       117,098            2019

In [125]:
df_1 = pd.read_csv("CSV Brute Files/1.csv")
df_1.head()
df_1 = df_1.iloc[1:,[0,5]]
countries = df_1.iloc[:,0].values
test = countries[0]
print(type(test))
print(test)

<class 'str'>
Monaco *


In [126]:
new_countries = clean_name(countries, True)
new_countries.shape

(216,)

In [147]:
estimate = df_1.iloc[:,1].values
test2 = estimate[0]
print(test2)

190,532


In [150]:
test2 = float(str(test2).replace(',','.'))
print(test2)
print(type(test2))

190.532
<class 'float'>


In [171]:
new_estimate = np.zeros(estimate.shape[0], dtype=float)
for i in range(estimate.shape[0]):
    new_estimate[i] = float(str(estimate[i]).replace(',','.'))